name: Update README with Visitor Data

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalışacak
  push:
    branches:
      - main   # Ana dalda (main) bir push olduğunda tetiklenecek

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Read visitor data from JSON
      run: |
        VISITOR_DATA=$(cat data.json)
        TOTAL_VISITORS=$(echo "$VISITOR_DATA" | jq '.totalVisitors')
        CURRENT_VISITORS=$(echo "$VISITOR_DATA" | jq '.currentVisitors')
        SERVICE_VISITORS=$(echo "$VISITOR_DATA" | jq '.servicePageVisitors')

        echo "Total Visitors: $TOTAL_VISITORS" > visitors.txt
        echo "Current Visitors: $CURRENT_VISITORS" >> visitors.txt
        echo "Service Page Visitors: $SERVICE_VISITORS" >> visitors.txt

    - name: Update README.md
      run: |
        echo "## Site İstatistikleri" > README.md
        echo "Toplam Ziyaterçi: $(cat visitors.txt | head -n 1)" >> README.md
        echo "Anlık Siteyi Kullananlar: $(cat visitors.txt | head -n 2 | tail -n 1)" >> README.md
        echo "Hizmetten Yararlananlar: $(cat visitors.txt | tail -n 1)" >> README.md

    - name: Commit and push changes to README
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "Update README with latest visitor stats"
        git push
